# Generated by Django 5.1.1 on 2024-10-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(default='null', max_length=200)),
                ('userNumber', models.CharField(max_length=6)),
                ('forceWin', models.BooleanField()),
                ('pcNumber', models.CharField(max_length=6)),
                ('userVictory', models.BooleanField()),
            ],
        ),
    ]
