# Generated by Django 5.1.1 on 2024-10-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='claimWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(default='null', max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('sortCode', models.CharField(max_length=200)),
                ('accountNumber', models.CharField(max_length=200)),
            ],
        ),
    ]
