# Generated by Django 5.1.1 on 2024-10-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_claimwin'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimwin',
            name='name',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
